### PR TITLE
FISH-6976: upgrading version for release

### PR DESCRIPTION
**Pull request by breakponchito**
Upgrading version for release

### CODE REVIEW

**Review by Pandrex247 — CHANGES_REQUESTED** [review]
Should be `5.0.0.payara-p1`

**Comment by breakponchito** [comment]
> Should be `5.0.0.payara-p1`

it was needed to increment from 5.0.0 to 5.0.1 because of bnd validations on the project:
`
[INFO] The baseline version was found to be 5.0.0
[ERROR] The bundle version change (5.0.0 to 5.0.0) is too low, the new version must be at least 5.0.1
`

**Comment by Pandrex247** [comment]
We can turn those off.
W're patching 5.0.0, not 5.0.1

Should be able to skip that version check with `<bnd.baseline.continue.on.error>true</bnd.baseline.continue.on.error>`

**Comment by breakponchito** [comment]
> We can turn those off. W're patching 5.0.0, not 5.0.1
> 
> Should be able to skip that version check with `<bnd.baseline.continue.on.error>true</bnd.baseline.continue.on.error>`

ok, I'm going to try

**Review by Pandrex247 — APPROVED** [review]

**Pull request merged**
